stages:
  - build
  - deploy

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  before_script:
    - mkdir -p ~/.kube
    - ls -la
    # - echo $KUBECONFIG
    - cp $KUBECONFIG ~/.kube/config
  script:
    # - cat ~/.kube/config
    # - kubectl config get-contexts
    # - kubectl get nodes
    - kubectl create secret docker-registry registry-gitlab
      --docker-server=$CI_REGISTRY
      --docker-username=$USERNAME
      --docker-password=$PASSWORD
    - kubectl apply -f ./deploy
    - kubectl get po