import { Metadata } from 'next'
import './global.css'
import Navbar from './components/narbar/Navbar'
import Footer from './components/footer/Footer'
// import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Next.my',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className='container'>
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
