import { Metadata } from 'next'
import './global.css'
import Navbar from './components/Navbar'
// import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Next.my',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {/* <nav>
          <a href="/">Logo</a>
          // <a href="/">Home</a>
          <Link href="/">Home</Link>
          <a href="/login">Login</a>
        </nav> */}
        <Navbar />
        {children}
      </body>
    </html>
  )
}
