apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-my
spec:
  replicas: 3
  selector:
    matchLabels:
      app: next-my
  template:
    metadata:
      labels:
        app: next-my
    spec:
      containers:
      - image: registry.thaibevapp.com/root/next.my:latest
        name: next-my
        ports:
        - containerPort: 3000
